sudo: false
language: ruby
rvm:
  - 2.4.1
bundler_args: "--without development"
script:
- bundle exec rspec
env:
  global:
    secure: 2jYKwznltkcfY8wCVXhOwW3w88XX8tqA5xyyDltuWWRArYSD4U7+upSXIsD+uOf6HU7JTHvypxEJjmZL9PTgSH2RDLJ9AK0nRNXzBn6nGQROh34G6ih03IZ9ZBO/OX1QFlUgXBblSxcQzDOsgpH3g2FYTL0173E+TdPnJEif6jYsoJPFVhXa68U1qwNIzjcjkGV2fXGQiITa059Xjm+GMmUO3cMTjKBD9D3j041aVhJOMflmgA8a/lt41OMg62nC388ACyIdTx45eTVy44tAzMkY/Eo5mOyTMRmcrnEZCnbE3iELlknNbheAQy2we2fmW8RAia7IlvzM3BB/CKKRD3299WSLlKq4F8TzuhGRvlU04v81y9uvKFTwOGnUeLx7ssyl0xkBGyE0Qp44O85FSwb+TYKe67ovNCpi+bMgtGQb+a3zRncUtzUcSaw5mzHvCQDDzJoLT2w7txXLu99+WFTxuRRsbhWzilDuqhlRczWb1P6L9Wtbmgjoh6mTSWSyPfTufK9HnUNY3To0dq6PYD80O/00b6DwjTdQOF6peOElvjnZ4q8pfrxCbD4mHcTyDPCtiLsN/Q3JqrJkUiDX0zhYOXFQ89yI1GGxgSjLLkbsALJiQerPkC1UQep9yz5VzgdCvUl7gFjY5AM5kA17Y+OjzZQRmCMocOWqs42N4lM=
