sudo: false
language: ruby
rvm:
  - 2.4.1
bundler_args: "--without development"
script:
- bundle exec rspec
env:
  global:
    secure: kv3TVhAvWVrWgI6saMf53A1jyD6SwMQpDrLSfzE9bGexccS1dwfk7XFGAY52sutcm2Sq/NHpmLOxI10xWzJhbCAP8Pi8KVB5xHItqecrjHJoSG609b3DLWXSlKOjHHQOqz62wRbtz49pVK1UsNzqsLrVZMb9GmSXw1ChVMorJ3Sv6W2ax3gH8aC9cwhh5IKhy90JqzJcBZyCkBQtaLmXwLMmkpQZA4i7F5bVjvSgMzBncvsRUqqLIKrl7aJhaAlMybAC7ADzxjuLOsPAcuqz0EdXRF1wyL4VfXGGePz5VvZaj/ZLeRqMoiyFAhvIRG7YLJDsKXqEraPXj3YdwzwAPnuDjJywXWhN0yb4U5RnINm5zo+Y/BBTly6kUAhaNBQsbwvBkYG+KBMNYhZBSlUTsu8DDq3I1UCyAWo61syUSaOV9xgAeGyavzxL2t/Ef+zgSK9QS9CWT0CVXwvkvN2qxnizZTO2rRVho8tUbmvup+TFa487zKZjk/+9cVdZycF8QZ5qsJz5diZTX2V3sT2HCykxuaoi7dNsdeQNZuurf3/JbHc+nCC4bfbfqNMs9LES58/cdKGfIwvp8/a8rQDsXft6nOamCOAqEVGLxHVNeG46FIN66UmRS4OslN+brY7dchCrVnAYPcHelgC7XM8NsDxpIXFBLnmDZZ7gs7ppdF4=
