name: check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2', '3.3', 'head']
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec --fail-fast
      - name: Check source files using `rubocop`
        run: rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'
      - name: Run codecov on latest ruby
        if: matrix.ruby == '3.3'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
