name: no-running-test-droplets
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up latest Ruby
        uses: ruby/setup-ruby@v1
      - name: Build and test with Rake
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec --fail-fast
      - name: Check that there is no running test droplets
        run: bundle exec rake check_no_test_droplet
